services:
  pg:
    image: postgres:15-alpine
    container_name: owasp-pg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=owasp
    volumes:
      - owasp:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  owasp:
